from fastapi import APIRouter, Depends, HTTPException, Query
from typing import List
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession
from datetime import datetime, timezone # <--- Added timezone
from src.models import Task, TaskCreate, TaskUpdate, TaskPublic, User
from src.db import get_session
from src.auth.auth_handler import get_current_user

router = APIRouter(tags=["tasks"])

@router.get("/api/{user_id}/tasks", response_model=List[TaskPublic])
async def get_user_tasks(
    user_id: str, 
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
    limit: int = Query(100, ge=1, le=1000),
    offset: int = Query(0, ge=0)
):
    if str(current_user.id) != user_id:
        raise HTTPException(status_code=403, detail="Not authorized")
    
    statement = (
        select(Task)
        .where(Task.user_id == user_id)
        .order_by(Task.created_at.desc())
        .offset(offset)
        .limit(limit)
    )
    result = await session.exec(statement)
    return result.all()

# ✅ FIXED: task_id is now str
@router.get("/api/{user_id}/tasks/{task_id}", response_model=TaskPublic)
async def get_single_task(
    user_id: str, 
    task_id: str, # <--- Changed Int to Str
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    if str(current_user.id) != user_id:
        raise HTTPException(status_code=403, detail="Not authorized")
    
    statement = select(Task).where(Task.id == task_id, Task.user_id == user_id)
    result = await session.exec(statement)
    task = result.first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    return task

@router.post("/api/{user_id}/tasks", response_model=TaskPublic)
async def create_task(
    user_id: str,
    task_data: TaskCreate,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    if str(current_user.id) != user_id:
        raise HTTPException(status_code=403, detail="Not authorized")
    
    # Create task (ID is auto-generated by model as UUID string)
    task = Task(**task_data.model_dump())
    task.user_id = user_id 
    session.add(task)
    await session.commit()
    await session.refresh(task)
    return task

# ✅ FIXED: task_id is now str
@router.put("/api/{user_id}/tasks/{task_id}", response_model=TaskPublic)
async def update_task(
    user_id: str,
    task_id: str, # <--- Changed Int to Str
    task_data: TaskUpdate,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    if str(current_user.id) != user_id:
        raise HTTPException(status_code=403, detail="Not authorized")
    
    statement = select(Task).where(Task.id == task_id, Task.user_id == user_id)
    result = await session.exec(statement)
    task = result.first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    for field, value in task_data.model_dump(exclude_unset=True).items():
        setattr(task, field, value)
    
    # ✅ FIXED: Use timezone-aware datetime
    task.updated_at = datetime.now(timezone.utc)
    
    session.add(task)
    await session.commit()
    await session.refresh(task)
    return task

# ✅ FIXED: task_id is now str
@router.delete("/api/{user_id}/tasks/{task_id}")
async def delete_task(
    user_id: str,
    task_id: str, # <--- Changed Int to Str
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    if str(current_user.id) != user_id:
        raise HTTPException(status_code=403, detail="Not authorized")
    
    statement = select(Task).where(Task.id == task_id, Task.user_id == user_id)
    result = await session.exec(statement)
    task = result.first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    await session.delete(task)
    await session.commit()
    return {"message": "Task deleted successfully"}

# ✅ FIXED: task_id is now str
@router.patch("/api/{user_id}/tasks/{task_id}/complete", response_model=TaskPublic)
async def toggle_task_completion(
    user_id: str,
    task_id: str, # <--- Changed Int to Str
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    if str(current_user.id) != user_id:
        raise HTTPException(status_code=403, detail="Not authorized")
    
    statement = select(Task).where(Task.id == task_id, Task.user_id == user_id)
    result = await session.exec(statement)
    task = result.first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    task.completed = not task.completed
    # ✅ FIXED: Use timezone-aware datetime
    task.updated_at = datetime.now(timezone.utc)
    
    session.add(task)
    await session.commit()
    await session.refresh(task)
    return task